### ISSUE TITLE
Burner Phone suggestion - remove case sensitivity

### ISSUE THREAD

**Issue by olx-i** [xplanthris/SimpleBuckshotRouletteCounter#3]
Right now if a lowercase letter is given as an input for the burner phone, it gives out an "Invalid unput" error.

**Comment by xplanthris-zz** [comment]
Yeah, I will update the code to allow you to in every case type l, b, live, blank

**Comment by xplanthris-zz** [comment]
Fixed in commit ddc248a thanks
